debug: true
server:
  port: 8080

dsl:
  restful:
    base-package: com.github.alphafoxz
    include-modules:
      - spring-boot-starter-restful-dsl
      - spring-boot-starter-restful-dsl-test
#    http-controller-class: com.github.alphafoxz.spring_boot_starter_restful_dsl.standard.HttpController
    http-controller-class: com.github.alphafoxz.spring_boot_starter_restful_dsl_test.standard.HttpController
    page-class: com.github.alphafoxz.spring_boot_starter_restful_dsl_test.standard.Page
